from __future__ import annotations

import bcrypt
from fastapi import HTTPException, Request


def verify_password(password: str, password_hash: str) -> bool:
    """Accept the bcrypt hashes generated by PHP password_hash()."""
    encoded = password_hash.encode()
    if encoded.startswith(b"$2y$"):
        encoded = b"$2b$" + encoded[4:]
    try:
        return bcrypt.checkpw(password.encode(), encoded)
    except (ValueError, TypeError):
        return False


async def require_admin(request: Request) -> str:
    username = request.session.get("username")
    if not isinstance(username, str) or not username:
        raise HTTPException(status_code=401, detail="请先登录")
    return username
