from __future__ import annotations

import bcrypt
from collections import deque
from threading import Lock
from time import monotonic


def verify_password(password: str, password_hash: str) -> bool:
    """Accept the bcrypt hashes generated by PHP password_hash()."""
    encoded = password_hash.encode()
    if encoded.startswith(b"$2y$"):
        encoded = b"$2b$" + encoded[4:]
    try:
        return bcrypt.checkpw(password.encode(), encoded)
    except (ValueError, TypeError):
        return False


class LoginRateLimiter:
    """Small in-process guard for password guessing; no database schema is required."""

    def __init__(self, max_failures: int, window_seconds: int) -> None:
        self._max_failures = max_failures
        self._window_seconds = window_seconds
        self._failures: dict[str, deque[float]] = {}
        self._lock = Lock()

    def retry_after(self, key: str) -> int:
        now = monotonic()
        with self._lock:
            attempts = self._prune(key, now)
            if len(attempts) < self._max_failures:
                return 0
            return max(1, int(self._window_seconds - (now - attempts[0])) + 1)

    def record_failure(self, key: str) -> None:
        now = monotonic()
        with self._lock:
            self._prune(key, now).append(now)

    def reset(self, key: str) -> None:
        with self._lock:
            self._failures.pop(key, None)

    def _prune(self, key: str, now: float) -> deque[float]:
        attempts = self._failures.setdefault(key, deque())
        while attempts and now - attempts[0] >= self._window_seconds:
            attempts.popleft()
        return attempts
